name = "d1-auth-example"
main = "src/index.ts"
compatibility_date = "2024-09-01"


[[d1_databases]]
binding = "DB"
database_name = "your-db-name"
database_id = "8a257505-af13-4da6-9d98-611585abaa58"


[vars]
SALT_TOKEN = "sadfasdghjyt45645t"
